Fügt Terminate Process Node hinzu
5minds/node-red-contrib-processcube pull request #41
Opened 2024-08-22 14:02 UTC by luisthieme

2024-08-22 19:11 UTC, moellenbeck requested changes
Es scheint, dass die Dokumentation und der Code etwas ungereimt zu sein.

2024-08-22 19:11 UTC, moellenbeck commented on process-terminate.js
> +                .terminateProcessInstance(msg.payload, engine.identity)
in der Hilfe steht, es muss `processInstanceId` als Input vorhanden sein. Was ist denn hier korrekt?

2024-08-22 20:52 UTC, luisthieme commented
> Es scheint, dass die Dokumentation und der Code etwas ungereimt zu sein.

Ich überarbeite das morgen nochmal. Bin nicht ganz fertig geworden heute mach ich aber morgen direkt als erstes.

2024-08-23 14:16 UTC, moellenbeck approved these changes

2024-08-26 05:45 UTC, merged