Fix: UserTask-Input
5minds/node-red-contrib-processcube pull request #47
Opened 2024-09-16 08:58 UTC by luisthieme

Closes #45

2024-09-16 11:38 UTC, roblen45 requested changes

2024-09-16 11:38 UTC, roblen45 commented on usertask-input.js
> +                    } else if (config.sendtype === 'multi' && matchingFlowNodes?.userTasks?.length > 1) {
Was passiert, wenn ich multi ausgewählt habe und nur eine UserTask zurück kommt?

2024-09-16 12:31 UTC, luisthieme commented on usertask-input.js
> +                    } else if (config.sendtype === 'multi' && matchingFlowNodes?.userTasks?.length > 1) {
Dann wird  der danach folgende If-Else-Block ausgeführt, und die Usertask wird als einzelne Task gesendet, da 'Send as Array' nicht ausgewählt ist.

2024-09-17 21:18 UTC, roblen45 approved these changes

2024-09-18 08:57 UTC, merged